# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=225)),
                ('personalPhotoUrl', models.CharField(blank=True, max_length=225, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=225, null=True)),
                ('pinyinName', models.CharField(blank=True, db_index=True, max_length=225, null=True)),
                ('nickName', models.CharField(blank=True, db_index=True, max_length=225, null=True)),
                ('pinyinNick', models.CharField(blank=True, db_index=True, max_length=225, null=True)),
                ('workNo', models.CharField(max_length=64)),
                ('postName', models.CharField(max_length=64)),
                ('deptName', models.CharField(db_index=True, max_length=64)),
                ('workStatus', models.CharField(db_index=True, max_length=64)),
                ('gmtLeave', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
