# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='UID',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pinyinName',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pinyinNick',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workNo',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workStatus',
            field=models.CharField(db_index=True, max_length=4),
        ),
    ]
