# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0002_auto_20180615_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('gmt_create', models.DateTimeField()),
                ('gmt_modified', models.DateTimeField(blank=True, null=True)),
                ('message_body', models.TextField()),
                ('is_consumed', models.IntegerField()),
                ('lock_str', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
