# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0004_auto_20180615_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicate',
            name='gmt_create',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='communicate',
            name='gmt_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
